export const API_REGISTER = 'http://localhost:8080/api/auth/signup'
export const API_EXIST_MAIL = 'http://localhost:8080/api/auth/exist-email?'
export const API_POST_DETAIL = 'http://localhost:8080/api/post-detail?post_id='
export const API_DISTRICT ='http://localhost:8080/api/address/district'
export const API_PROVINCE = 'http://localhost:8080/api/address/province'
export const API_RATE = 'http://localhost:8080/api/post-detail/rate-post?post_id='
export const API_ROOM_TYPE = 'http://localhost:8080/api/room-type/'
export const API_PROFILE = 'http://localhost:8080/api/auth/profile'
export const API_GET_DISTRICT_BY_PROVINCE ='http://localhost:8080/api/address/district-by-provinceID?province-id='
export const API_POSTING =  'http://localhost:8080/api/posting/create-posting'
export const API_UTILITYS = 'http://localhost:8080/api/utility'
